blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/R0159-3L/.github/discussions
    about: Ask questions and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/R0159-3L/.github
    about: Check out our documentation
